### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by C4BR3R4** [elsiff/MoreFish#15]
Error starting server: https://pastebin.com/mwNF3fP6
```
[17:15:21] [Server thread/INFO]: [MoreFish] Enabling MoreFish v2.1.3
[17:15:21] [Server thread/INFO]: [MoreFish] Loaded 24 fish successfully.
[17:15:21] [Server thread/WARN]: java.lang.NullPointerException
[17:15:21] [Server thread/WARN]: 	at me.elsiff.morefish.protocol.UpdateChecker.loadNewVersion(UpdateChecker.java:42)
[17:15:21] [Server thread/WARN]: 	at me.elsiff.morefish.protocol.UpdateChecker.<init>(UpdateChecker.java:18)
[17:15:21] [Server thread/WARN]: 	at me.elsiff.morefish.MoreFish.onEnable(MoreFish.java:54)
[17:15:21] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[17:15:21] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[17:15:21] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[17:15:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
[17:15:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
[17:15:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
[17:15:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
[17:15:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[17:15:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[17:15:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[17:15:21] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by C4BR3R4** [comment]
Revive

**Comment by EdRatner** [comment]
I am also getting this error loading up my server
