### ISSUE TITLE
1.8 console error

### ISSUE THREAD

**Issue by successed** [elsiff/MoreFish#38]
[15:17:56] [Server thread/ERROR]: Could not load 'plugins/more-fish-3.0.2-all.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/bukkit/NamespacedKey
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:331) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:254) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/NamespacedKey
	at me.elsiff.morefish.fishing.competition.FishingCompetitionTimerBarHandler.<init>(FishingCompetitionTimerBarHandler.kt:24) ~[?:?]
	at me.elsiff.morefish.fishing.competition.FishingCompetitionHost.<init>(FishingCompetitionHost.kt:20) ~[?:?]
	at me.elsiff.morefish.MoreFish.<init>(MoreFish.kt:43) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_212]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_212]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:77) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.NamespacedKey
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
	at me.elsiff.morefish.fishing.competition.FishingCompetitionTimerBarHandler.<init>(FishingCompetitionTimerBarHandler.kt:24) ~[?:?]
	at me.elsiff.morefish.fishing.competition.FishingCompetitionHost.<init>(FishingCompetitionHost.kt:20) ~[?:?]
	at me.elsiff.morefish.MoreFish.<init>(MoreFish.kt:43) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_212]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_212]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:77) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	... 6 more

**Comment by successed** [comment]
[15:20:53] [Server thread/ERROR]: Error occurred while enabling MoreFish v2.1.3 (Is it up to date?)
java.lang.NullPointerException
	at me.elsiff.morefish.manager.FishManager.getIcon(FishManager.java:166) ~[?:?]
	at me.elsiff.morefish.manager.FishManager.createCustomFish(FishManager.java:100) ~[?:?]
	at me.elsiff.morefish.manager.FishManager.loadFishList(FishManager.java:52) ~[?:?]
	at me.elsiff.morefish.manager.FishManager.<init>(FishManager.java:37) ~[?:?]
	at me.elsiff.morefish.MoreFish.onEnable(MoreFish.java:52) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[15:20:53] [Server thread/INFO]: [MoreFish] Disabling MoreFish v2.1.3

**Comment by FunkyNico** [comment]
Same here i get this issue trying to use it on a 1.8.8 server:

`[02:52:25 ERROR]: Could not load 'plugins\more-fish-3.0.2-all.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/bukkit/NamespacedKey
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[StellarSpigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:335) ~[StellarSpigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:252) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:286) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:211) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:594) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/NamespacedKey
        at me.elsiff.morefish.fishing.competition.FishingCompetitionTimerBarHandler.<init>(FishingCompetitionTimerBarHandler.kt:24) ~[?:?]
        at me.elsiff.morefish.fishing.competition.FishingCompetitionHost.<init>(FishingCompetitionHost.kt:20) ~[?:?]
        at me.elsiff.morefish.MoreFish.<init>(MoreFish.kt:43) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_241]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_241]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_241]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:77) ~[StellarSpigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:130) ~[StellarSpigot.jar:git-TacoSpigot-04511af6]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.NamespacedKey
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[StellarSpigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[StellarSpigot.jar:git-TacoSpigot-04511af6]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
        at me.elsiff.morefish.fishing.competition.FishingCompetitionTimerBarHandler.<init>(FishingCompetitionTimerBarHandler.kt:24) ~[?:?]
        at me.elsiff.morefish.fishing.competition.FishingCompetitionHost.<init>(FishingCompetitionHost.kt:20) ~[?:?]
        at me.elsiff.morefish.MoreFish.<init>(MoreFish.kt:43) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_241]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_241]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_241]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:77) ~[StellarSpigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:130) ~[StellarSpigot.jar:git-TacoSpigot-04511af6]
        ... 6 more`
